language: perl
perl:
  - "5.24-shrplib"
  - "5.22-shrplib"
  - "5.20-shrplib"
  - "5.18-shrplib"
env: 
  - 'PERL_CPANM_OPT="--notest --force --skip-satisfied"'
  - 'PATH=$PATH:`pwd`/jellyfish-2.2.6'
before_install:
  - "wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.6/jellyfish-2.2.6.tar.gz"
  - "tar zxvf jellyfish-2.2.6.tar.gz"
  - "cd jellyfish-2.2.6/ && ./configure --prefix=`pwd` && make -j 1 && make install"
  # bootstrap modules needed to manipulate dist
  - "yes no | cpanm --force --notest Bio::Perl"
