language: perl
perl:
  - "5.24-shrplib"
  - "5.22-shrplib"
  - "5.20-shrplib"
  - "5.18-shrplib"
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
  # bootstrap modules needed to manipulate dist
  - "yes no | cpanm --force --notest Bio::Perl"
