language: perl
perl: 5.24-shrplib
env: PERL_CPANM_OPT="--mirror http://cpan.mirrors.travis-ci.org  --mirror http://cpan.cpantesters.org/ --mirror http://search.cpan.org/CPAN --cascade-search --notest --force --skip-satisfied"
before_install:
  - "pwd && echo $PATH"
  - "wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.6/jellyfish-2.2.6.tar.gz"
  - "tar zxvf jellyfish-2.2.6.tar.gz"
  - "cd jellyfish-2.2.6/ && ./configure --prefix=`pwd` && make -j 1 && make install"
  #- "which jellyfish"
  #- "ls bin"
